import { importBodyMeasurements } from "@/app/health-data/actions";
import { HealthHeader } from "@/app/health-data/health-header";
import { requireUser } from "@/lib/auth";

type Props = { searchParams: Promise<{ imported?: string | string[] }> };

export default async function ImportMeasurementsPage({ searchParams }: Props) {
  await requireUser();
  const rawImported = (await searchParams).imported;
  const imported = Array.isArray(rawImported) ? rawImported[0] : rawImported;
  return <main className="min-h-screen bg-stone-50 pb-12 text-stone-900"><HealthHeader title="Importar medidas do Excel" description="Exporte ou salve sua planilha como CSV e organize os dados no modelo abaixo." backHref="/health-data/measurements" backLabel="Medidas corporais" /><div className="mx-auto grid max-w-5xl gap-6 px-5 py-6 sm:px-8 lg:grid-cols-[1fr_360px]"> <section className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6">{imported && <div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">Importação concluída: {imported} linha(s) processada(s).</div>}<h2 className="text-xl font-semibold">Enviar arquivo CSV</h2><p className="mt-2 text-sm leading-6 text-stone-600">O arquivo pode ter datas em <strong>DD/MM/AAAA</strong> ou <strong>AAAA-MM-DD</strong>. Use vírgula ou ponto nos decimais. O limite é 2 MB.</p><form action={importBodyMeasurements} className="mt-6 space-y-4"><label className="block text-sm font-medium">Arquivo CSV<input type="file" name="file" accept=".csv,text/csv" required className="mt-2 block w-full cursor-pointer rounded-xl border border-stone-300 bg-stone-50 px-3 py-3 text-sm file:mr-4 file:rounded-lg file:border-0 file:bg-rose-100 file:px-3 file:py-2 file:font-semibold file:text-rose-800" /></label><button className="rounded-xl bg-rose-700 px-5 py-3 font-semibold text-white hover:bg-rose-800">Importar dados</button></form><div className="mt-7 rounded-2xl bg-amber-50 p-4 text-sm leading-6 text-amber-900"><strong>Importante:</strong> intervalos como “62-69 cm” não são importados porque não representam uma medida exata. Substitua pelo valor que deseja guardar.</div></section><aside className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-semibold">Formato esperado</h2><p className="mt-2 text-sm leading-6 text-stone-600">Uma linha representa uma medida em uma data.</p><pre className="mt-4 overflow-x-auto rounded-xl bg-stone-900 p-4 text-xs leading-6 text-stone-100">date;body_part;value;unit;instructions{"\n"}2023-01-09;Bíceps Direito;30;cm;{"\n"}2023-01-09;Peitoral;92;cm;Mamilo / tórax</pre><p className="mt-4 text-sm leading-6 text-stone-600">Se <strong>body_part</strong> for “Peso”, o valor será enviado para Meu Peso em kg. Partes do corpo ainda inexistentes serão criadas automaticamente.</p><a href="/templates/body-measurements.csv" download className="mt-5 inline-flex rounded-xl border border-rose-300 px-4 py-2.5 text-sm font-semibold text-rose-800 hover:bg-rose-50">↓ Baixar modelo CSV</a></aside></div></main>;
}
